// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHZuFYjD0-1jXNZFtdWg8RsI7I_7kg30E',
    appId: '1:441246959087:web:9e34f1f704fa448017a21a',
    messagingSenderId: '441246959087',
    projectId: 'login-4799c',
    authDomain: 'login-4799c.firebaseapp.com',
    storageBucket: 'login-4799c.firebasestorage.app',
    measurementId: 'G-DHZN4FNH3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMbqJmr_8hcMs3-0Sz4WEfNxVqhqfIcKM',
    appId: '1:441246959087:android:39890806cb68837717a21a',
    messagingSenderId: '441246959087',
    projectId: 'login-4799c',
    storageBucket: 'login-4799c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACp7bHCBTt_Hq4U_lMvpeslqLoicB-cr8',
    appId: '1:441246959087:ios:d3ae3fea56b1b84b17a21a',
    messagingSenderId: '441246959087',
    projectId: 'login-4799c',
    storageBucket: 'login-4799c.firebasestorage.app',
    iosBundleId: 'com.example.mob3Login107Halil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACp7bHCBTt_Hq4U_lMvpeslqLoicB-cr8',
    appId: '1:441246959087:ios:d3ae3fea56b1b84b17a21a',
    messagingSenderId: '441246959087',
    projectId: 'login-4799c',
    storageBucket: 'login-4799c.firebasestorage.app',
    iosBundleId: 'com.example.mob3Login107Halil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHZuFYjD0-1jXNZFtdWg8RsI7I_7kg30E',
    appId: '1:441246959087:web:06c88ce0ffeb4acf17a21a',
    messagingSenderId: '441246959087',
    projectId: 'login-4799c',
    authDomain: 'login-4799c.firebaseapp.com',
    storageBucket: 'login-4799c.firebasestorage.app',
    measurementId: 'G-JSG8V1JS8D',
  );
}
